framework:
    secret: '%env(APP_SECRET)%'

    default_locale: fr

    session: true   


when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
