vich_uploader:
    db_driver: orm

    mappings:
        events_covers:
            uri_prefix: /uploads/events
            upload_destination: '%kernel.project_dir%/public/uploads/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        events_images:
            uri_prefix: /uploads/eventImages
            upload_destination: '%kernel.project_dir%/public/uploads/eventImages'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            